name: Update Wiki by city
on:
  push:
    paths:
      - '*.md'
      - '.github/scripts/update_wiki_by_city.py'
      - '.github/workflows/update-wiki.yml'
jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Run update_wiki_by_city.py
        run: |
          pip install --upgrade pip
          python .github/scripts/update_wiki_by_city.py
      - name: Commit Wiki update
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git diff --cached --quiet || git commit -m 'Auto-update README.md (by city and stack)'
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
